=== flensrocker/vdr-plugin-skindesigner/dtd/setup.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT setup (menu,translations)>
<!ELEMENT menu (submenu | parameter)*>
<!ELEMENT translations (token)*>

<!ELEMENT submenu (submenu | parameter)*>
<!ATTLIST submenu
  name NMTOKEN #REQUIRED
  displaytext CDATA #REQUIRED
  >

<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter
  name NMTOKEN #REQUIRED
  type (int|bool) #REQUIRED
  min NMTOKEN #IMPLIED
  max NMTOKEN #IMPLIED
  displaytext CDATA #REQUIRED
  >

<!ELEMENT token (trans)+>
<!ATTLIST token
  name CDATA #REQUIRED>

<!ELEMENT trans (#PCDATA)>
<!ATTLIST trans
  lang NMTOKEN #REQUIRED>

=== flensrocker/vdr-plugin-skindesigner/skins/metrixhd/setup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "../../dtd/setup.dtd">

<setup>
    <menu>
        <parameter type="int" name="fadetime" min="0" max="1000" displaytext="{tr(fadetext)}">0</parameter>
        <parameter type="bool" name="showdevices" displaytext="{tr(showdevices)}">0</parameter>
    </menu>

    <translations>
        <token name="tr(fadetext)">
            <trans lang="en_EN">Fade time in ms</trans>
            <trans lang="de_DE">Einblendzeit in ms</trans>
            <trans lang="fi_FI">Häivytyksen kesto [ms]</trans>
        </token>
        <token name="tr(showdevices)">
            <trans lang="en_EN">Show DVB device info when switching channel</trans>
            <trans lang="de_DE">DVB Karten Info beim Umschalten anzeigen</trans>
            <trans lang="fi_FI">Näytä DVB-tiedot kanavanvaihdossa</trans>
        </token>
    </translations>
</setup>

=== flensrocker/vdr-plugin-skindesigner/skins/blackhole/setup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "../../dtd/setup.dtd">

<setup>
    <!--
    define all your parameters here which should be configurable via
    OSD and the skindesigner setup menu.
    Parameters must have type "bool" or "integer". For "bool" Parameters
    a choice yes/no is shown in the setup menu, a "integer" parameter
    can be configured to a value between "min" and "max". If "min" is not
    set, "0" is the minimum, if "max" is not set, "1000" is maximum.
    "displayname" is used to display the option in the setup menu.
    The configured parameter value is the default value.
    -->
    <parameters>
        <parameter type="bool" name="showdevices" displaytext="{tr(showdevices)}">0</parameter>
        <parameter type="bool" name="showposter" displaytext="{tr(showpostertext)}">1</parameter>
        <parameter type="bool" name="showmainmenuicons" displaytext="{tr(showmainmenuicons)}">1</parameter>
        <parameter type="int" name="fadetime" min="0" max="1000" displaytext="{tr(fadetext)}">300</parameter>
        <parameter type="int" name="nummenuitemsmain" min="6" max="30" displaytext="{tr(nummenuitemsmain)}">10</parameter>
        <parameter type="int" name="nummenuitems" min="6" max="30" displaytext="{tr(nummenuitems)}">10</parameter>
        <parameter type="int" name="nummenuitemsdefault" min="6" max="30" displaytext="{tr(nummenuitemsdefault)}">16</parameter>
        <parameter type="bool" name="showsubtitle" displaytext="{tr(showsubtitle)}">1</parameter>
    </parameters>

    <!--
    translations of displaytexts
    -->
    <translations>
        <token name="tr(showdevices)">
            <trans lang="en_EN">Show DVB device info when switching channel</trans>
            <trans lang="de_DE">DVB Karten Info beim Umschalten anzeigen</trans>
            <trans lang="fi_FI">Näytä DVB-tiedot kanavanvaihdossa</trans>
        </token>
        <token name="tr(showpostertext)">
            <trans lang="en_EN">Show Poster when switching channel</trans>
            <trans lang="de_DE">Poster beim Umschalten anzeigen</trans>
            <trans lang="fi_FI">Näytä posterit kanavanvaihdossa</trans>
        </token>
        <token name="tr(showmainmenuicons)">
            <trans lang="en_EN">Show Icons in Main Menu</trans>
            <trans lang="de_DE">Icons im Hauptmenü anzeigen</trans>
            <trans lang="fi_FI">Näytä ikonit päävalikossa</trans>
        </token>
        <token name="tr(fadetext)">
            <trans lang="en_EN">Fade time in ms (needs VDR restart)</trans>
            <trans lang="de_DE">Einblendzeit in ms (erfordert VDR Neustart)</trans>
            <trans lang="fi_FI">Häivytyksen kesto [ms] (uud.käynnistys)</trans>
        </token>
        <token name="tr(nummenuitemsmain)">
            <trans lang="en_EN">Items in main menu (needs VDR restart)</trans>
            <trans lang="de_DE">Elemente im Hauptmenü (erfordert VDR Neustart)</trans>
            <trans lang="fi_FI">Valinnat päävalikossa (uud.käynnistys)</trans>
        </token>
        <token name="tr(nummenuitems)">
            <trans lang="en_EN">Items in schedules, timers, ... menus (needs VDR restart)</trans>
            <trans lang="de_DE">Elemente in Programm, Timer, ... Menüs (erfordert VDR Neustart)</trans>
            <trans lang="fi_FI">Valinnat alivalikoissa (uud.käynnistys)</trans>
        </token>
        <token name="tr(nummenuitemsdefault)">
            <trans lang="en_EN">Items in default list menu (needs VDR restart)</trans>
            <trans lang="de_DE">Elemente im Standard ListenMenü (erfordert VDR Neustart)</trans>
            <trans lang="fi_FI">Valinnat valikkolistoissa (uud.käynnistys)</trans>
        </token>
        <token name="tr(showsubtitle)">
            <trans lang="en_EN">Show shorttexts in schedules menus</trans>
            <trans lang="de_DE">Kurztexte im Programm Menü anzeigen</trans>
            <trans lang="fi_FI">Näytä lyhyet kuvaukset ohjelmaoppaassa</trans>
        </token>
    </translations>
</setup>

=== flensrocker/vdr-plugin-skindesigner/skins/nopacity/setup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "../../dtd/setup.dtd">

<setup>
    <!--
    define all your parameters here which should be configurable via
    OSD and the skindesigner setup menu.
    Parameters must have type "bool" or "integer". For "bool" Parameters
    a choice yes/no is shown in the setup menu, a "integer" parameter
    can be configured to a value between "min" and "max". If "min" is not
    set, "0" is the minimum, if "max" is not set, "1000" is maximum.
    "displayname" is used to display the option in the setup menu.
    The configured parameter value is the default value.
    -->
    <parameters>
        <parameter type="bool" name="showposter" displaytext="{tr(showpostertext)}">1</parameter>
        <parameter type="bool" name="showweather" displaytext="{tr(showweather)}">1</parameter>
        <parameter type="int" name="fadeTime" min="0" max="1000" displaytext="{tr(fadeText)}">300</parameter>
        <parameter type="int" name="transparency" min="0" max="30" displaytext="{tr(transparency)}">20</parameter>
    </parameters>

    <!--
    translations of displaytexts
    -->
    <translations>
        <token name="tr(showpostertext)">
            <trans lang="en_EN">Show Poster when switching channel</trans>
            <trans lang="de_DE">Poster beim Umschalten anzeigen</trans>
        </token>       
        <token name="tr(showweather)">
            <trans lang="en_EN">Show Weather in infobar</trans>
            <trans lang="de_DE">Wetter in Infobar anzeigen</trans>
        </token>
        <token name="tr(fadeText)">
            <trans lang="en_EN">Fade time in ms (needs VDR restart)</trans>
            <trans lang="de_DE">Einblendzeit in ms (erfordert VDR Neustart)</trans>
        </token>
        <token name="tr(transparency)">
            <trans lang="en_EN">Transpareny channel, replay and volume (needs VDR restart)</trans>
            <trans lang="de_DE">Transparenz bei Kanal,Wiedergabe und Lautst√§rke (erfordert VDR Neustart)</trans>
        </token>
    </translations>
</setup>
